### ISSUE TITLE
Update and refactor examples

### ISSUE THREAD

**Issue by Maghnie** [RWTH-EBC/FiLiP#237]
**Is your feature request related to a problem? Please describe.**
Most of the [examples](https://github.com/RWTH-EBC/FiLiP/tree/master/examples) haven't been updated since 2022, so now there's some deprecated code.

**Describe the solution you'd like**
Rerun the examples and update any code as necessary. 

**Additional context**
Along the way, typos may be fixed, and examples may be clarified. 

- [x] basic examples
    - [x] refactor
    - [x] fix pydantic bug
- [ ] ngsi_v2
    - [ ] refactor
    - [ ] fix simple_ql bug

**Nice-to-haves**
- [ ] Use colored logs
- [ ] Add descriptions to the log messages as well (in addition to those in the comments)

**Comment by Maghnie** [comment]
Bug encountered in [e02_ngsi_v2_context_relationships.py](https://github.com/RWTH-EBC/FiLiP/blob/master/examples/ngsi_v2/e02_ngsi_v2_context_relationships.py):

```python
2024-02-01 17:54:24,333 __main__ INFO: [NamedContextAttribute(name='refStore', type='Relationship', value='urn:ngsi-ld:Store:001', metadata={}), NamedContextAttribute(name='refProduct', type='Relationship', value='urn:ngsi-ld:Product:001', metadata={})]
2024-02-01 17:54:24,341 __main__ INFO: [ContextEntity(id='urn:ngsi-ld:InventoryItem:001', type='InventoryItem', refProduct=ContextAttribute(type='Relationship', value='urn:ngsi-ld:Product:001', metadata={}), 
refStore=ContextAttribute(type='Relationship', value='urn:ngsi-ld:Store:001', metadata={}), stockCount=ContextAttribute(type='Integer', value=10000, metadata={}))]
refProduct==urn:ngsi-ld:Product:001
Traceback (most recent call last):
  File "d:\Repos\04-OpenSource\FiLiP\examples\ngsi_v2\e02_ngsi_v2_context_relationships.py", line 176, in <module>
    cb_client.get_entity_list(q="refStore!=urn:ngsi-ld:Store:002"))
  File "C:\Users\mmg\AppData\Local\anaconda3\envs\filip\lib\site-packages\filip\clients\ngsi_v2\cb.py", line 366, in get_entity_list
    q = QueryString.parse_str(q)
  File "C:\Users\mmg\AppData\Local\anaconda3\envs\filip\lib\site-packages\filip\utils\simple_ql.py", line 307, in parse_str
    return QueryString(qs=qs)
  File "C:\Users\mmg\AppData\Local\anaconda3\envs\filip\lib\site-packages\filip\utils\simple_ql.py", line 213, in __init__
    qs = self.__check_arguments(qs=qs)
  File "C:\Users\mmg\AppData\Local\anaconda3\envs\filip\lib\site-packages\filip\utils\simple_ql.py", line 230, in __check_arguments
    qs[idx] = QueryStatement(*item)
TypeError: filip.utils.simple_ql.QueryStatement() argument after * must be an iterable, not NoneType
```

caused by using **string** queries: `cb_client.get_entity_list(q="refProduct==urn:ngsi-ld:Product:001")`

but this works:

```python
query = QueryString(qs=[('refProduct', '==', 'urn:ngsi-ld:Product:001')])
logger.info(cb_client.get_entity_list(q=query))
```

and used for now as a workaround.

A more long-term fix should probably be in this function: 

https://github.com/RWTH-EBC/FiLiP/blob/a263c55a3310766b731a18697e43d55031cedd96/filip/utils/simple_ql.py#L174
