### ISSUE TITLE
filip 0.3.0 not working with Python 3.9

### ISSUE THREAD

**Issue by j-pick** [RWTH-EBC/FiLiP#242]
**Describe the bug**
It is not possible to import the ContextBroker with the settings described below.

**To Reproduce**
1. Create a new venv with python 3.9 as base interpreter (more specifically, 3.9.7)
2. Install filip 0.3.0 via pip
3. Execute the following code:

```
from filip.clients.ngsi_v2 import ContextBrokerClient

def test_cb():
    cb = ContextBrokerClient()

if __name__ == '__main__':
    test_cb()

```

The code fails at the import statement already with the following error:

```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from filip.clients.ngsi_v2 import ContextBrokerClient
  File "venv\lib\site-packages\filip\__init__.py", line 5, in <module>
    from filip.clients.ngsi_v2 import HttpClient
  File "venv\lib\site-packages\filip\clients\ngsi_v2\__init__.py", line 4, in <module>
    from .cb import ContextBrokerClient
  File "venv\lib\site-packages\filip\clients\ngsi_v2\cb.py", line 35, in <module>
    from filip.models.ngsi_v2.subscriptions import Subscription, Message
  File "venv\lib\site-packages\filip\models\ngsi_v2\subscriptions.py", line 308, in <module>
    class Subscription(BaseModel):
  File "venv\lib\site-packages\filip\models\ngsi_v2\subscriptions.py", line 362, in Subscription
    throttling: Optional[conint(strict=True, ge=0,)] = Field(
  File "venv\lib\site-packages\pydantic\types.py", line 225, in conint
    annotated_types.Interval(gt=gt, ge=ge, lt=lt, le=le),
TypeError: Interval() takes no arguments

Process finished with exit code 1
```

**Expected behavior**

I expect the import to work.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 
 - Version 10

**Additional context**

With python 3.10 as base interpreter instead of 3. it runs without any problem.

**Comment by djs0109** [comment]
@j-pick it is a known problem, the official conclusion is not to use `python 3.9.7`. For further information see here https://github.com/pydantic/pydantic/issues/7544
